/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entidades.Historico;
import entidades.Personagem;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import persistencia.*;

/**
 *
 * @author 08050520
 */
public class TelaCriarPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialJogo
     */
    private int avatar;

    public TelaCriarPersonagem() {
        initComponents();

        ImageIcon img = new ImageIcon("src/imagem/lutadora_CabeloCastanho.jpg");
        Image image = img.getImage();
        Image newimg = image.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img = new ImageIcon(newimg);

        ImageIcon img2 = new ImageIcon("src/imagem/lutador_Asiatico.jpg");
        Image image2 = img2.getImage();
        Image newimg2 = image2.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img2 = new ImageIcon(newimg2);

        ImageIcon img3 = new ImageIcon("src/imagem/lutador_CabeloCastanho.jpeg");
        Image image3 = img3.getImage();
        Image newimg3 = image3.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img3 = new ImageIcon(newimg3);

        ImageIcon img4 = new ImageIcon("src/imagem/lutador_Loiro.jpg");
        Image image4 = img4.getImage();
        Image newimg4 = image4.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img4 = new ImageIcon(newimg4);

        ImageIcon img5 = new ImageIcon("src/imagem/lutador_Negro.jpg");
        Image image5 = img5.getImage();
        Image newimg5 = image5.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img5 = new ImageIcon(newimg5);

        ImageIcon img6 = new ImageIcon("src/imagem/lutadora_Asiatica.jpg");
        Image image6 = img6.getImage();
        Image newimg6 = image6.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img6 = new ImageIcon(newimg6);

        ImageIcon img10 = new ImageIcon("src/imagem/lutadora_Loira.jpg");
        Image image10 = img10.getImage();
        Image newimg10 = image10.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img10 = new ImageIcon(newimg10);

        ImageIcon img11 = new ImageIcon("src/imagem/lutadora_Negra_CabeloBlackPower.jpg");
        Image image11 = img11.getImage();
        Image newimg11 = image11.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
        img11 = new ImageIcon(newimg11);

        avatar3.setIcon(img);
        avatar8.setIcon(img2);
        avatar7.setIcon(img3);
        avatar6.setIcon(img4);
        avatar5.setIcon(img5);
        avatar4.setIcon(img6);
        avatar2.setIcon(img10);
        avatar1.setIcon(img11);

        voltar.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeAvatares = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        textoCriarSeuPersonagem = new javax.swing.JLabel();
        textoNome = new javax.swing.JLabel();
        textoIdade = new javax.swing.JLabel();
        textoPeso = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoIdade = new javax.swing.JSlider();
        campoIdade.setLabelTable(campoIdade.createStandardLabels(3));
        ok = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        textoEscolhaOSeuAvatar = new javax.swing.JLabel();
        campoPeso = new javax.swing.JFormattedTextField();
        botaoAvatar1 = new javax.swing.JRadioButton();
        botaoAvatar2 = new javax.swing.JRadioButton();
        botaoAvatar4 = new javax.swing.JRadioButton();
        botaoAvatar7 = new javax.swing.JRadioButton();
        botaoAvatar8 = new javax.swing.JRadioButton();
        botaoAvatar5 = new javax.swing.JRadioButton();
        botaoAvatar6 = new javax.swing.JRadioButton();
        botaoAvatar3 = new javax.swing.JRadioButton();
        avatar8 = new javax.swing.JLabel();
        avatar7 = new javax.swing.JLabel();
        avatar6 = new javax.swing.JLabel();
        avatar5 = new javax.swing.JLabel();
        avatar4 = new javax.swing.JLabel();
        avatar3 = new javax.swing.JLabel();
        avatar1 = new javax.swing.JLabel();
        avatar2 = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoCriarSeuPersonagem.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        textoCriarSeuPersonagem.setForeground(new java.awt.Color(255, 255, 255));
        textoCriarSeuPersonagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCriarSeuPersonagem.setText("CRIE SEU PERSONAGEM");
        jPanel1.add(textoCriarSeuPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 225, -1));

        textoNome.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        textoNome.setForeground(new java.awt.Color(255, 255, 255));
        textoNome.setText("NOME:");
        jPanel1.add(textoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        textoIdade.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        textoIdade.setForeground(new java.awt.Color(255, 255, 255));
        textoIdade.setText("IDADE:");
        jPanel1.add(textoIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        textoPeso.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        textoPeso.setForeground(new java.awt.Color(255, 255, 255));
        textoPeso.setText("PESO:");
        jPanel1.add(textoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        campoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNomeKeyPressed(evt);
            }
        });
        jPanel1.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 38));

        campoIdade.setForeground(new java.awt.Color(35, 35, 35));
        campoIdade.setMajorTickSpacing(10);
        campoIdade.setMaximum(45);
        campoIdade.setMinimum(18);
        campoIdade.setMinorTickSpacing(2);
        campoIdade.setPaintLabels(true);
        campoIdade.setPaintTicks(true);
        campoIdade.setValue(31);
        campoIdade.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        jPanel1.add(campoIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, 60));
        campoIdade.getAccessibleContext().setAccessibleName("");
        campoIdade.getAccessibleContext().setAccessibleDescription("");

        ok.setText("Ok");
        ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 80, 80));

        voltar.setBackground(new java.awt.Color(242, 242, 242));
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao_branco.png"))); // NOI18N
        voltar.setText("Voltar");
        voltar.setBorder(null);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 60));

        textoEscolhaOSeuAvatar.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoEscolhaOSeuAvatar.setForeground(new java.awt.Color(255, 255, 255));
        textoEscolhaOSeuAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEscolhaOSeuAvatar.setText("ESCOLHA O SEU ICONE");
        jPanel1.add(textoEscolhaOSeuAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 24, 235, -1));

        campoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesoActionPerformed(evt);
            }
        });
        campoPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPesoKeyTyped(evt);
            }
        });
        jPanel1.add(campoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, 40));

        grupoDeAvatares.add(botaoAvatar1);
        botaoAvatar1.setContentAreaFilled(false);
        botaoAvatar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar1ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 80));

        grupoDeAvatares.add(botaoAvatar2);
        botaoAvatar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar2ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 110, 80));

        grupoDeAvatares.add(botaoAvatar4);
        botaoAvatar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar4ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, 80));

        grupoDeAvatares.add(botaoAvatar7);
        botaoAvatar7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar7ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, 80));

        grupoDeAvatares.add(botaoAvatar8);
        botaoAvatar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar8ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 110, 80));

        grupoDeAvatares.add(botaoAvatar5);
        botaoAvatar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar5ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, 80));

        grupoDeAvatares.add(botaoAvatar6);
        botaoAvatar6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar6ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 110, 80));

        grupoDeAvatares.add(botaoAvatar3);
        botaoAvatar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAvatar3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoAvatar3ItemStateChanged(evt);
            }
        });
        jPanel1.add(botaoAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 110, 80));

        avatar8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 80, 80));

        avatar7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 80, 80));

        avatar6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 80, 80));

        avatar5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 80, 80));

        avatar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 80, 80));

        avatar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 80, 80));

        avatar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 80, 80));

        avatar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 80, 80));

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ringue.jpg"))); // NOI18N
        jPanel1.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new TelaInicial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        Personagem personagem;
        String nome = campoNome.getText();
        int idade = campoIdade.getValue();
        double peso;
        if (campoPeso.getText().equals("")) {
            peso = 0;
        } else {
            peso = Double.parseDouble(campoPeso.getText());
        }
        Historico historico = new Historico();

        try {
            personagem = new Personagem(nome, idade, peso, avatar, historico);
            PersonagemDAO p = PersonagemDAO.getInstance();
            if (p.inserir(personagem)) {
                new TelaAcoesDoPersonagem(personagem).setVisible(true);
                this.setVisible(false);
            } else new TelaPopUp("O número maxímo de Personagens foi atingido. Delete um personagem para criar outro!").setVisible(true);
        } catch (Exception e) {
            new TelaPopUp(e.getMessage()).setVisible(true);
        }

    }//GEN-LAST:event_okActionPerformed

    private void botaoAvatar1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 1;
        }
    }//GEN-LAST:event_botaoAvatar1ItemStateChanged

    private void botaoAvatar2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar2ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 2;
        }
     }//GEN-LAST:event_botaoAvatar2ItemStateChanged

    private void botaoAvatar3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar3ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 3;
        }
    }//GEN-LAST:event_botaoAvatar3ItemStateChanged

    private void botaoAvatar4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar4ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 4;
        }
    }//GEN-LAST:event_botaoAvatar4ItemStateChanged

    private void botaoAvatar5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar5ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 5;
        }
    }//GEN-LAST:event_botaoAvatar5ItemStateChanged

    private void botaoAvatar6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar6ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 6;
        }
    }//GEN-LAST:event_botaoAvatar6ItemStateChanged

    private void botaoAvatar7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar7ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 7;
        }
    }//GEN-LAST:event_botaoAvatar7ItemStateChanged

    private void botaoAvatar8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoAvatar8ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.avatar = 8;
        }
    }//GEN-LAST:event_botaoAvatar8ItemStateChanged

    private void campoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesoActionPerformed

    private void campoPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesoKeyTyped
        String caracteres = "0123456789.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_campoPesoKeyTyped

    private void campoNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeKeyPressed
        if (campoNome.getText().length() > 10) {
            campoNome.setText(campoNome.getText().substring(0, 10));
        }
    }//GEN-LAST:event_campoNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JLabel avatar5;
    private javax.swing.JLabel avatar6;
    private javax.swing.JLabel avatar7;
    private javax.swing.JLabel avatar8;
    private javax.swing.JRadioButton botaoAvatar1;
    private javax.swing.JRadioButton botaoAvatar2;
    private javax.swing.JRadioButton botaoAvatar3;
    private javax.swing.JRadioButton botaoAvatar4;
    private javax.swing.JRadioButton botaoAvatar5;
    private javax.swing.JRadioButton botaoAvatar6;
    private javax.swing.JRadioButton botaoAvatar7;
    private javax.swing.JRadioButton botaoAvatar8;
    private javax.swing.JSlider campoIdade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JFormattedTextField campoPeso;
    private javax.swing.ButtonGroup grupoDeAvatares;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    private javax.swing.JLabel textoCriarSeuPersonagem;
    private javax.swing.JLabel textoEscolhaOSeuAvatar;
    private javax.swing.JLabel textoIdade;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoPeso;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
