/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entidades.Personagem;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author danie
 */
public class TelaAposentado extends javax.swing.JFrame {

    /**
     * Creates new form TelaAposentar
     */
    
    private static Personagem personagem;
    
    public TelaAposentado(Personagem personagem) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.setLocationRelativeTo(null);
        
        this.personagem = personagem;
        
        textoPartidaJogada.setText("Partidas Jogadas: " + personagem.getHistorico().getPartidasJogadas());
        textoPartidaGanha.setText("Partidas Ganhas: " + this.personagem.getHistorico().getPartidasGanhas());
        textoPartidaPerdida.setText("Partidas Perdidas: " + this.personagem.getHistorico().getPartidasPerdidas());
        
        if (personagem.getCod_avatar() == 1) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_Negra_CabeloBlackPower.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(170,150, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 2) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_Loira.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(170, 150, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 3) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_CabeloCastanho.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(170, 150, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 4) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_Asiatica.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(170, 150, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 5) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_Negro.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(170, 150, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 6) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_Loiro.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(170, 150, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 7) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_CabeloCastanho.jpeg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(170, 150, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 8) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_Asiatico.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(175, 114, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoAposentad = new javax.swing.JLabel();
        textoPartidaJogada = new javax.swing.JLabel();
        botaoRetornar = new javax.swing.JButton();
        textoPartidaGanha = new javax.swing.JLabel();
        textoPartidaPerdida = new javax.swing.JLabel();
        fotoAvatar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoAposentad.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        textoAposentad.setForeground(new java.awt.Color(255, 255, 255));
        textoAposentad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoAposentad.setText("Aposentado(a)");
        jPanel1.add(textoAposentad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 401, -1));

        textoPartidaJogada.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textoPartidaJogada.setForeground(new java.awt.Color(255, 255, 255));
        textoPartidaJogada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPartidaJogada.setText("Partidas Jogadas: 100");
        jPanel1.add(textoPartidaJogada, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 57, -1, -1));

        botaoRetornar.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        botaoRetornar.setText("Retornar ao Menu Inicial");
        botaoRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRetornarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 39));

        textoPartidaGanha.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textoPartidaGanha.setForeground(new java.awt.Color(255, 255, 255));
        textoPartidaGanha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPartidaGanha.setText("Partidas Ganhas: 80");
        jPanel1.add(textoPartidaGanha, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 101, 166, -1));

        textoPartidaPerdida.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textoPartidaPerdida.setForeground(new java.awt.Color(255, 255, 255));
        textoPartidaPerdida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPartidaPerdida.setText("Partidas Perdidas: 20");
        jPanel1.add(textoPartidaPerdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 145, -1, -1));

        fotoAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fotoAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 57, 170, 114));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/luvas.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRetornarActionPerformed
        new TelaInicial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoRetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAposentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAposentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAposentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAposentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAposentado(personagem).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRetornar;
    private javax.swing.JLabel fotoAvatar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoAposentad;
    private javax.swing.JLabel textoPartidaGanha;
    private javax.swing.JLabel textoPartidaJogada;
    private javax.swing.JLabel textoPartidaPerdida;
    // End of variables declaration//GEN-END:variables
}
