/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entidades.Personagem;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import persistencia.PersonagemDAO;

/**
 *
 * @author danie
 */
public class TelaCarregar extends javax.swing.JFrame {

    /**
     * Creates new form telaCarregar
     */
    Personagem personagem1;
    Personagem personagem2;
    Personagem personagem3;

    public TelaCarregar() {
        initComponents();
        jButton4.setBackground(new Color(0, 0, 0, 0));
        excluirSave1.setBackground(new Color(0, 0, 0, 0));
        excluirSave2.setBackground(new Color(0, 0, 0, 0));
        excluirSave3.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        PersonagemDAO p = PersonagemDAO.getInstance();

        ArrayList<Personagem> personagens = p.pesquisarTudo();
        Iterator i = personagens.iterator();

        if (i.hasNext()) {
            personagem1 = (Personagem) i.next();
        }
        if (i.hasNext()) {
            personagem2 = (Personagem) i.next();
        }
        if (i.hasNext()) {
            personagem3 = (Personagem) i.next();
        }

        if (personagem1 != null) {
            this.save1.setText(personagem1.getNome() + " (" + personagem1.getIdade() + "anos)" + " - "
                    + personagem1.getHistorico().getPartidasJogadas() + " J | "
                    + personagem1.getHistorico().getPartidasGanhas() + " G | "
                    + personagem1.getHistorico().getPartidasPerdidas() + " P");
        } else {
            this.save1.setText("VAZIO");
        }
        if (personagem2 != null) {
            this.save2.setText(personagem2.getNome() + " (" + personagem2.getIdade() + " anos)" + " - "
                    + personagem2.getHistorico().getPartidasJogadas() + " J | "
                    + personagem2.getHistorico().getPartidasGanhas() + " G | "
                    + personagem2.getHistorico().getPartidasPerdidas() + " P");
        } else {
            this.save2.setText("VAZIO");
        }
        if (personagem3 != null) {
            this.save3.setText(personagem3.getNome() + " (" + personagem3.getIdade() + "anos)" + " - "
                    + personagem3.getHistorico().getPartidasJogadas() + " J | "
                    + personagem3.getHistorico().getPartidasGanhas() + " G | "
                    + personagem3.getHistorico().getPartidasPerdidas() + " P");
        } else {
            this.save3.setText("VAZIO");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        save1 = new javax.swing.JButton();
        save2 = new javax.swing.JButton();
        save3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        excluirSave1 = new javax.swing.JButton();
        excluirSave2 = new javax.swing.JButton();
        excluirSave3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carregar Jogo anterior");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 387, -1));

        save1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        save1.setText("Save 1");
        save1.setToolTipText("");
        save1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel1.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 35));

        save2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        save2.setText("Save 2");
        save2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });
        jPanel1.add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 280, 35));

        save3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        save3.setText("Save 3");
        save3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });
        jPanel1.add(save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 280, 35));

        jButton4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao_branco.png"))); // NOI18N
        jButton4.setText("Voltar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 34));

        excluirSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lixeira_branca.png"))); // NOI18N
        excluirSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirSave1ActionPerformed(evt);
            }
        });
        jPanel1.add(excluirSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, 40));

        excluirSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lixeira_branca.png"))); // NOI18N
        excluirSave2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirSave2ActionPerformed(evt);
            }
        });
        jPanel1.add(excluirSave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 40, 40));

        excluirSave3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lixeira_branca.png"))); // NOI18N
        excluirSave3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirSave3ActionPerformed(evt);
            }
        });
        jPanel1.add(excluirSave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo_Carregar.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
         if (personagem1 != null) {
            new TelaAcoesDoPersonagem(personagem1).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_save1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TelaInicial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed
         if (personagem3 != null) {
            new TelaAcoesDoPersonagem(personagem3).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_save3ActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        if (personagem2 != null) {
            new TelaAcoesDoPersonagem(personagem2).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_save2ActionPerformed

    private void excluirSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirSave1ActionPerformed
         if (personagem1 != null) {
        PersonagemDAO p = PersonagemDAO.getInstance();
        p.excluir(Integer.toString(personagem1.getId()));
        this.setVisible(false);
        new TelaCarregar().setVisible(true);
         }
    }//GEN-LAST:event_excluirSave1ActionPerformed

    private void excluirSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirSave2ActionPerformed
         if (personagem2 != null) {
        PersonagemDAO p = PersonagemDAO.getInstance();
        p.excluir(Integer.toString(personagem2.getId()));
        this.setVisible(false);
        new TelaCarregar().setVisible(true);
         }
    }//GEN-LAST:event_excluirSave2ActionPerformed

    private void excluirSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirSave3ActionPerformed
         if (personagem3 != null) {
        PersonagemDAO p = PersonagemDAO.getInstance();
        p.excluir(Integer.toString(personagem3.getId()));
        this.setVisible(false);
        new TelaCarregar().setVisible(true);
         }
    }//GEN-LAST:event_excluirSave3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluirSave1;
    private javax.swing.JButton excluirSave2;
    private javax.swing.JButton excluirSave3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save1;
    private javax.swing.JButton save2;
    private javax.swing.JButton save3;
    // End of variables declaration//GEN-END:variables
}
