/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controle.Combate;
import entidades.Classificado;
import entidades.Personagem;
import java.awt.Color;
import java.awt.Image;
import java.util.Objects;
import javax.swing.ImageIcon;
import persistencia.ClassificacaoDAO;
import persistencia.PersonagemDAO;

/**
 *
 * @author danie
 */
public class TelaAcoesDoPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaPersonagem
     *
     */
    private static Personagem personagem;

    public TelaAcoesDoPersonagem(Personagem personagem) {
        Objects.requireNonNull(personagem, "Personagem não pode ser nulo");

        initComponents();

        this.personagem = personagem;

        textoNome.setText(personagem.getNome());
        textoPeso.setText(personagem.getPeso().toString());
        textoIdade.setText(personagem.getIdade() + " Anos");

        if (personagem.getCod_avatar() == 1) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_Negra_CabeloBlackPower.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 2) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_Loira.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 3) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_CabeloCastanho.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 4) {
            ImageIcon img = new ImageIcon("src/imagem/lutadora_Asiatica.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 5) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_Negro.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 6) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_Loiro.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 7) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_CabeloCastanho.jpeg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }
        if (personagem.getCod_avatar() == 8) {
            ImageIcon img = new ImageIcon("src/imagem/lutador_Asiatico.jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(130, 170, java.awt.Image.SCALE_SMOOTH);
            img = new ImageIcon(newimg);
            fotoAvatar.setIcon(img);
        }

        if (personagem.isAposentado()) {
            botaoAposentar.setEnabled(false);
            botaoLutar.setEnabled(false);
        }
        botaoVoltar.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fotoAvatar = new javax.swing.JLabel();
        textoNome = new javax.swing.JLabel();
        textoIdade = new javax.swing.JLabel();
        textoPeso = new javax.swing.JLabel();
        botaoLutar = new javax.swing.JButton();
        botaoAposentar = new javax.swing.JButton();
        botaoHistorico = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fotoAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fotoAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(fotoAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 20, 127, 138));

        textoNome.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        textoNome.setForeground(new java.awt.Color(255, 255, 255));
        textoNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNome.setText(" Darqui");
        jPanel1.add(textoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

        textoIdade.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        textoIdade.setForeground(new java.awt.Color(255, 255, 255));
        textoIdade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIdade.setText("Idade: 18");
        jPanel1.add(textoIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 126, -1));

        textoPeso.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        textoPeso.setForeground(new java.awt.Color(255, 255, 255));
        textoPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPeso.setText("Peso Leve");
        jPanel1.add(textoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 57, 126, 16));

        botaoLutar.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoLutar.setText("Lutar");
        botaoLutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoLutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLutarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 120, 103, 38));

        botaoAposentar.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoAposentar.setText("Aposentar");
        botaoAposentar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAposentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAposentarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAposentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 20, 103, 38));

        botaoHistorico.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoHistorico.setText("Historico");
        botaoHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 70, 103, 38));

        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao_branco.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 126, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/acoes.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLutarActionPerformed
        Combate combate = new Combate(personagem);
        new TelaCombate(combate).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoLutarActionPerformed

    private void botaoAposentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAposentarActionPerformed
        personagem.Aposentar();
        try {
            PersonagemDAO p = PersonagemDAO.getInstance();
            ClassificacaoDAO c = ClassificacaoDAO.getInstance();
            Classificado classificado = new Classificado(personagem.getNome(), personagem.getIdade(), personagem.getPeso().getCod(), personagem.getHistorico().getPartidasJogadas(), personagem.getHistorico().getPartidasGanhas(), personagem.getHistorico().getPartidasPerdidas());
            p.editar(personagem);
            c.inserir(classificado);

            new TelaAposentado(personagem).setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            new TelaPopUp(e.getMessage()).setVisible(true);
        }
    }//GEN-LAST:event_botaoAposentarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaInicial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHistoricoActionPerformed
        new TelaHistorico(personagem.getHistorico()).setVisible(true);
    }//GEN-LAST:event_botaoHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAcoesDoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAcoesDoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAcoesDoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAcoesDoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAcoesDoPersonagem(personagem).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAposentar;
    private javax.swing.JButton botaoHistorico;
    private javax.swing.JButton botaoLutar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel fotoAvatar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoIdade;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoPeso;
    // End of variables declaration//GEN-END:variables
}
