/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controle.Combate;
import java.awt.Color;
import java.util.Objects;
import persistencia.PersonagemDAO;

/**
 *
 * @author danie
 */
public class TelaChute extends javax.swing.JFrame {

    /**
     * Creates new form TelaSoco
     */
    private static Combate combate;

    public TelaChute(Combate combate) {
        initComponents();

        this.setLocationRelativeTo(null);

        Objects.requireNonNull(combate, "Tela de Combate não pode ser nulo");

        this.combate = combate;

        botaoVoltar.setBackground(new Color(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        textoChute = new javax.swing.JLabel();
        botaoChutePaia = new javax.swing.JButton();
        botaoBicao = new javax.swing.JButton();
        botaoVoadora = new javax.swing.JButton();
        botaoVoadoraDeDoisPes = new javax.swing.JButton();
        textoCusto1 = new javax.swing.JLabel();
        textoCusto2 = new javax.swing.JLabel();
        textoCusto3 = new javax.swing.JLabel();
        textoCusto4 = new javax.swing.JLabel();
        textoAtaque1 = new javax.swing.JLabel();
        textoAtaque2 = new javax.swing.JLabel();
        textoAtaque4 = new javax.swing.JLabel();
        textoEficacia1 = new javax.swing.JLabel();
        textoEficacia2 = new javax.swing.JLabel();
        textoEficacia4 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        textoCusto5 = new javax.swing.JLabel();
        botaoRapaoDeBrigadiano = new javax.swing.JButton();
        textoAtaque5 = new javax.swing.JLabel();
        textoEficacia5 = new javax.swing.JLabel();
        textoAtaque3 = new javax.swing.JLabel();
        textoEficacia3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 350));

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoChute.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        textoChute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoChute.setText("Chutes");
        panel.add(textoChute, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 6, 157, -1));

        botaoChutePaia.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoChutePaia.setText("Chute Paia");
        botaoChutePaia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoChutePaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoChutePaiaActionPerformed(evt);
            }
        });
        panel.add(botaoChutePaia, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 63, 157, 40));

        botaoBicao.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoBicao.setText("Bicão");
        botaoBicao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoBicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBicaoActionPerformed(evt);
            }
        });
        panel.add(botaoBicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 109, 157, 40));

        botaoVoadora.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoVoadora.setText("Voadora");
        botaoVoadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoVoadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoadoraActionPerformed(evt);
            }
        });
        panel.add(botaoVoadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 201, 157, 40));

        botaoVoadoraDeDoisPes.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoVoadoraDeDoisPes.setText("Voadora de dois pés");
        botaoVoadoraDeDoisPes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoVoadoraDeDoisPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoadoraDeDoisPesActionPerformed(evt);
            }
        });
        panel.add(botaoVoadoraDeDoisPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 247, 157, 40));

        textoCusto1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoCusto1.setForeground(new java.awt.Color(0, 128, 0));
        textoCusto1.setText("Custo: 3");
        panel.add(textoCusto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 73, -1, -1));

        textoCusto2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoCusto2.setForeground(new java.awt.Color(0, 128, 0));
        textoCusto2.setText("Custo: 4");
        panel.add(textoCusto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 119, -1, -1));

        textoCusto3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoCusto3.setForeground(new java.awt.Color(0, 128, 0));
        textoCusto3.setText("Custo: 10");
        panel.add(textoCusto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 211, -1, -1));

        textoCusto4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoCusto4.setForeground(new java.awt.Color(0, 128, 0));
        textoCusto4.setText("Custo: 18");
        panel.add(textoCusto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 257, 60, -1));

        textoAtaque1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoAtaque1.setForeground(new java.awt.Color(255, 0, 0));
        textoAtaque1.setText("ATQ: 4");
        panel.add(textoAtaque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 73, 37, -1));

        textoAtaque2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoAtaque2.setForeground(new java.awt.Color(255, 0, 0));
        textoAtaque2.setText("ATQ: 7");
        panel.add(textoAtaque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 119, 37, -1));

        textoAtaque4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoAtaque4.setForeground(new java.awt.Color(255, 0, 0));
        textoAtaque4.setText("ATQ: 38");
        panel.add(textoAtaque4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 257, 42, -1));

        textoEficacia1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoEficacia1.setForeground(new java.awt.Color(51, 51, 51));
        textoEficacia1.setText("EFC: 75%");
        panel.add(textoEficacia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 51, -1));

        textoEficacia2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoEficacia2.setForeground(new java.awt.Color(51, 51, 51));
        textoEficacia2.setText("EFC: 60%");
        panel.add(textoEficacia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 119, -1, -1));

        textoEficacia4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoEficacia4.setForeground(new java.awt.Color(51, 51, 51));
        textoEficacia4.setText("EFC: 30%");
        panel.add(textoEficacia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 257, -1, -1));

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Botao.png"))); // NOI18N
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        panel.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 15, -1, -1));

        textoCusto5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoCusto5.setForeground(new java.awt.Color(0, 128, 0));
        textoCusto5.setText("Custo: 8");
        panel.add(textoCusto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 165, -1, -1));

        botaoRapaoDeBrigadiano.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoRapaoDeBrigadiano.setText("Rapão de Brigadiano");
        botaoRapaoDeBrigadiano.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoRapaoDeBrigadiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRapaoDeBrigadianoActionPerformed(evt);
            }
        });
        panel.add(botaoRapaoDeBrigadiano, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 155, -1, 40));

        textoAtaque5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoAtaque5.setForeground(new java.awt.Color(255, 0, 0));
        textoAtaque5.setText("ATQ: 14");
        panel.add(textoAtaque5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 165, 42, -1));

        textoEficacia5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoEficacia5.setForeground(new java.awt.Color(51, 51, 51));
        textoEficacia5.setText("EFC: 50%");
        panel.add(textoEficacia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 165, -1, -1));

        textoAtaque3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoAtaque3.setForeground(new java.awt.Color(255, 0, 0));
        textoAtaque3.setText("ATQ: 18");
        panel.add(textoAtaque3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 211, 42, -1));

        textoEficacia3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        textoEficacia3.setForeground(new java.awt.Color(51, 51, 51));
        textoEficacia3.setText("EFC: 40%");
        textoEficacia3.setToolTipText("");
        panel.add(textoEficacia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 211, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoChutePaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoChutePaiaActionPerformed
        String msg = combate.golpePesDoUser(1);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoChutePaiaActionPerformed

    private void botaoBicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBicaoActionPerformed
        String msg = combate.golpePesDoUser(2);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoBicaoActionPerformed

    private void botaoVoadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoadoraActionPerformed
        String msg = combate.golpePesDoUser(3);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoadoraActionPerformed

    private void botaoVoadoraDeDoisPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoadoraDeDoisPesActionPerformed
        String msg = combate.golpePesDoUser(4);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoadoraDeDoisPesActionPerformed

    private void botaoRapaoDeBrigadianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRapaoDeBrigadianoActionPerformed
        String msg = combate.golpePesDoUser(5);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoRapaoDeBrigadianoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaCombate(combate).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaChute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaChute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaChute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaChute(combate).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBicao;
    private javax.swing.JButton botaoChutePaia;
    private javax.swing.JButton botaoRapaoDeBrigadiano;
    private javax.swing.JButton botaoVoadora;
    private javax.swing.JButton botaoVoadoraDeDoisPes;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel textoAtaque1;
    private javax.swing.JLabel textoAtaque2;
    private javax.swing.JLabel textoAtaque3;
    private javax.swing.JLabel textoAtaque4;
    private javax.swing.JLabel textoAtaque5;
    private javax.swing.JLabel textoChute;
    private javax.swing.JLabel textoCusto1;
    private javax.swing.JLabel textoCusto2;
    private javax.swing.JLabel textoCusto3;
    private javax.swing.JLabel textoCusto4;
    private javax.swing.JLabel textoCusto5;
    private javax.swing.JLabel textoEficacia1;
    private javax.swing.JLabel textoEficacia2;
    private javax.swing.JLabel textoEficacia3;
    private javax.swing.JLabel textoEficacia4;
    private javax.swing.JLabel textoEficacia5;
    // End of variables declaration//GEN-END:variables
}
