/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entidades.Classificado;
import java.awt.Color;
import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;
import persistencia.ClassificacaoDAO;

/**
 *
 * @author 08050520
 */
public class TelaClassificacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaClassificacao2
     */
    private DefaultTableModel tableModel;
    private static TreeSet<Classificado> classificados;

    public TelaClassificacao(TreeSet<Classificado> c) {

        this.classificados = c;
        initComponents();
        configurarTabela();
        atualizarTabelaClassificados();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        texto = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Idade", "Peso", "Partidas", "Vitórias", "Derrotas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(22, 20, 740, 328);

        texto.setBackground(new java.awt.Color(255, 255, 255));
        texto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setText("Buscar Personagem:");
        jPanel1.add(texto);
        texto.setBounds(240, 360, 159, 19);
        jPanel1.add(campoBuscar);
        campoBuscar.setBounds(402, 354, 250, 25);

        buscar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 0));
        buscar.setText("Buscar");
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar);
        buscar.setBounds(658, 354, 104, 25);

        restart.setBackground(new Color (0, 0, 0, 0));
        restart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        restart.setForeground(new java.awt.Color(255, 255, 255));
        restart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/recarregar.png"))); // NOI18N
        restart.setText("Tabela Padrao");
        restart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        jPanel1.add(restart);
        restart.setBounds(70, 350, 150, 40);

        voltar.setBackground(new Color (0, 0, 0, 0));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao_branco.png"))); // NOI18N
        voltar.setToolTipText("");
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(20, 350, 36, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/classificacao.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 790, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        ClassificacaoDAO c = ClassificacaoDAO.getInstance();
        TreeSet<Classificado> tree = (TreeSet<Classificado>) c.pesquisar(this.campoBuscar.getText());
        if (tree != null) {
            this.classificados = tree;
            atualizarTabelaClassificados();
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        ClassificacaoDAO c = ClassificacaoDAO.getInstance();
        TreeSet<Classificado> tree = (TreeSet<Classificado>) c.pesquisarTudo();
        this.classificados = tree;
        atualizarTabelaClassificados();
    }//GEN-LAST:event_restartActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new TelaInicial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClassificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClassificacao(classificados).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton restart;
    private javax.swing.JLabel texto;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
    private void configurarTabela() {
        // Configura o DefaultTableModel para a jTable1
        tableModel = new DefaultTableModel(
                new Object[][]{}, // Dados iniciais (vazio)
                new String[]{"Posição","Nome", "Idade", "Peso", "Partidas", "Vitórias", "Derrotas"} // Nomes das colunas
        );

        jTable1.setModel(tableModel);
    }

    private void atualizarTabelaClassificados() {
        tableModel.setRowCount(0);

        for (Classificado c : this.classificados) {
            Object[] rowData = {
                c.getPosicao() + "º",
                c.getNome(),
                c.getIdade(),
                c.getPeso(),
                c.getPartidasJogadas(),
                c.getPartidasGanhas(),
                c.getPartidasPerdidas()
            };
            tableModel.addRow(rowData);
        }
    }

}
