/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controle.Combate;
import entidades.*;
import java.awt.Color;
import java.util.Objects;
import persistencia.PersonagemDAO;

/**
 *
 * @author danie
 */
public class TelaSoco extends javax.swing.JFrame {

    /**
     * Creates new form TelaSoco
     */
    private static Combate combate;

    public TelaSoco(Combate combate) {
        initComponents();

        this.setLocationRelativeTo(null);

        Objects.requireNonNull(combate, "Tela de Combate não pode ser nulo");

        this.combate = combate;

        botaoVoltar.setBackground(new Color(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoSocoPaia = new javax.swing.JButton();
        botaoSocoDeLado = new javax.swing.JButton();
        botaoSocoNoBucho = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botaoRetaoNoQueijo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        botaoGanchão = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Socos");

        botaoSocoPaia.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoSocoPaia.setText("Soco Paia");
        botaoSocoPaia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSocoPaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSocoPaiaActionPerformed(evt);
            }
        });

        botaoSocoDeLado.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoSocoDeLado.setText("Soco de Lado");
        botaoSocoDeLado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSocoDeLado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSocoDeLadoActionPerformed(evt);
            }
        });

        botaoSocoNoBucho.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoSocoNoBucho.setText("Soco no Bucho");
        botaoSocoNoBucho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSocoNoBucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSocoNoBuchoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        jLabel2.setText("Custo: 2");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 128, 0));
        jLabel4.setText("Custo: 4");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 128, 0));
        jLabel5.setText("Custo: 12");

        jLabel8.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("ATQ: 3");

        jLabel10.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("ATQ: 7");

        jLabel11.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("ATQ: 18");

        jLabel13.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("EFC: 80%");

        jLabel15.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("EFC: 60%");

        jLabel16.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("EFC: 40%");

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Botao.png"))); // NOI18N
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 128, 0));
        jLabel3.setText("Custo: 5");

        jLabel14.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("EFC: 55%");

        jLabel9.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("ATQ: 10");

        botaoRetaoNoQueijo.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoRetaoNoQueijo.setText("Retão no Queixo");
        botaoRetaoNoQueijo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoRetaoNoQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRetaoNoQueijoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 128, 0));
        jLabel6.setText("Custo: 10");

        botaoGanchão.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        botaoGanchão.setText("Ganchão");
        botaoGanchão.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoGanchão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGanchãoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("ATQ: 15");

        jLabel17.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("EFC: 60%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(19, 19, 19)
                                .addComponent(botaoSocoNoBucho, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(botaoGanchão, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(botaoRetaoNoQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(botaoSocoDeLado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(botaoSocoPaia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel13))))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoSocoPaia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoSocoDeLado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRetaoNoQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGanchão, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSocoNoBucho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSocoPaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSocoPaiaActionPerformed
        String msg = combate.golpesMaosDoUser(1);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoSocoPaiaActionPerformed

    private void botaoRetaoNoQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRetaoNoQueijoActionPerformed
        String msg = combate.golpesMaosDoUser(2);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoRetaoNoQueijoActionPerformed

    private void botaoSocoDeLadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSocoDeLadoActionPerformed
        String msg = combate.golpesMaosDoUser(3);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoSocoDeLadoActionPerformed

    private void botaoSocoNoBuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSocoNoBuchoActionPerformed
        String msg = combate.golpesMaosDoUser(4);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoSocoNoBuchoActionPerformed

    private void botaoGanchãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGanchãoActionPerformed
        String msg = combate.golpesMaosDoUser(5);
        if (combate.isCombateFinalizado() == true) {
            try {
                PersonagemDAO p = PersonagemDAO.getInstance();
                p.editar(combate.getPersonagem());
                new TelaDeVitoriaOuDerrota(combate).setVisible(true);
                new TelaPopUp(msg).setVisible(true);
            } catch (Exception e) {
                new TelaPopUp(e.getMessage()).setVisible(true);
            }
        } else {
            new TelaCombate(combate).setVisible(true);
            new TelaPopUp(msg).setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoGanchãoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaCombate(combate).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSoco(combate).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGanchão;
    private javax.swing.JButton botaoRetaoNoQueijo;
    private javax.swing.JButton botaoSocoDeLado;
    private javax.swing.JButton botaoSocoNoBucho;
    private javax.swing.JButton botaoSocoPaia;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
